[versions]
agp = "8.6.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
hilt = "2.51.1"
room = "2.6.1"
navigation = "2.7.7"
roomCommonJvm = "2.6.1"
roomRuntimeAndroid = "2.6.1"
foundationLayoutAndroid = "1.6.8"
composeIcons = "1.6.8"
material3Android = "1.2.1"
navigationCommonAndroid = "2.7.7"
navigationRuntimeAndroid = "2.9.8"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }

# Jetpack Compose & Navigation
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "foundationLayoutAndroid" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Android" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeIcons" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Room (Base de datos local)
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Hilt (Inyección de dependencias)
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

